(cl:in-package distributor-msg)
(cl:export '(PITCH-VAL
          PITCH
          ROLL-VAL
          ROLL
          YAW-VAL
          YAW
          ACC_X-VAL
          ACC_X
          ACC_Y-VAL
          ACC_Y
          ACC_Z-VAL
          ACC_Z
          GYRO_X-VAL
          GYRO_X
          GYRO_Y-VAL
          GYRO_Y
          GYRO_Z-VAL
          GYRO_Z
          PARO-VAL
          PARO
          PH-VAL
          PH
          WATER-VAL
          WATER
          TEMP-VAL
          TEMP
          MAG1-VAL
          MAG1
          MAG2-VAL
          MAG2
          MAG3-VAL
          MAG3
))